dist: bionic
language: generic
before_install:
# [WIP] attempting to run vagrant
  - cat /proc/cpuinfo
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add - && sudo sh -c "echo deb https://download.virtualbox.org/virtualbox/debian bionic contrib >> /etc/apt/sources.list" && sudo apt-get update && sudo apt-get install build-essential gcc make linux-headers-$(uname -r) virtualbox-6.0 && sudo usermod -aG vboxusers $(whoami)
  - wget https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.deb && sudo dpkg -i vagrant_2.2.5_x86_64.deb
  - vagrant init fedora/30-cloud-base && vagrant up && mkdir -p ~/.ssh && vagrant ssh-config >> ~/.ssh/config
  - ssh default dmesg && vagrant destroy -f
# Install Docker 18.09+ for enabling DOCKER_BUILDKIT
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo cat /etc/docker/daemon.json
# Apr 22, 2019: daemon.json contains `{"registry-mirrors": ["https://mirror.gcr.io"]}`, doesn't work well with BuildKit?
  - sudo rm -f /etc/docker/daemon.json
  - sudo systemctl restart docker
script:
# --progress=tty doesn't work with Travis: "This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log."
  - make _ci DOCKER_BUILDKIT=1 DOCKER_BUILD_FLAGS="--progress=plain"
