name: Release
on:
  push:
    tags:
    - 'v*'
env:
  DOCKER_BUILDKIT: 1
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
    - uses: actions/checkout@v2
    - run: make artifact
    - run: cat _artifact/SHA256SUMS
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
    - name: "Upload usernetes-x86_64.tbz"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: _artifact/usernetes-x86_64.tbz
        asset_name: usernetes-x86_64.tbz
        asset_content_type: application/octet-stream
    - name: "Upload SHA256SUMS"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: _artifact/SHA256SUMS
        asset_name: SHA256SUMS
        asset_content_type: application/octet-stream
    - name: "Upload SHA256SUMS (artifact)"
      uses: actions/upload-artifact@v1
      with:
        name: SHA256SUMS
        path: _artifact/SHA256SUMS
