name: Single Node
on:  
  workflow_call:
    inputs:
      container_engine:
        description: container engine
        type: string
        default: "docker"
      kubelet_port:
        description: kubelet serving port
        type: string
        default: "10250"
      flannel_port:
        description: flannel vxlan port
        type: string
        default: "8472"
      etcd_port:
        description: etcd service port
        type: string
        default: "2379"
      kube_apiserver_port:
        description: Kubernetes API server port
        # Using string, might be bug with number
        # https://github.com/orgs/community/discussions/67182
        type: string
        default: "6443"

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions
permissions: read-all

jobs:
  single-node:
    name: "Single node"
    runs-on: ubuntu-24.04
    timeout-minutes: 40
    env:
      CONTAINER_ENGINE: "${{ inputs.container_engine }}"
      PORT_KUBE_APISERVER: "${{ inputs.kube_apiserver_port }}"
      PORT_FLANNEL: "${{ inputs.flannel_port }}"
      PORT_KUBELET: "${{ inputs.kubelet_port }}"
      PORT_ETCD: "${{ inputs.etcd_port }}"
      KUBECONFIG: ./kubeconfig
    steps:
      - uses: actions/checkout@v4
      - name: Set up cgroup v2 delegation
        run: |
          sudo mkdir -p /etc/systemd/system/user@.service.d
          cat <<EOF | sudo tee /etc/systemd/system/user@.service.d/delegate.conf
          [Service]
          Delegate=cpu cpuset io memory pids
          EOF
          sudo systemctl daemon-reload
      - name: Remove preinstalled Moby
        # Preinstalled Moby does not contain dockerd-rootless-setuptool.sh
        run: sudo apt-get remove moby-engine-*
      - name: Set up Rootless Docker
        if: ${{ inputs.container_engine == 'docker' }}
        run: |
          set -eux -o pipefail
          curl https://get.docker.com | sudo sh
          sudo systemctl disable --now docker.socket docker.service
          sudo rm -rf /var/run/docker*
          dockerd-rootless-setuptool.sh install
          docker info
      - name: Set up Rootless nerdctl
        if: ${{ inputs.container_engine == 'nerdctl' }}
        run: |
          set -eux -o pipefail
          sudo ./init-host/init-host.root.d/install-nerdctl.sh
          ./init-host/init-host.rootless.sh
          nerdctl info
      - name: Set up Rootless Podman
        if: ${{ inputs.container_engine == 'podman' }}
        run: |
          set -eux -o pipefail
          sudo apt-get update
          sudo apt-get install -y podman-compose
          podman info
      - run: make up
      - run: sleep 5
      - run: make kubeadm-init
      - run: make install-flannel
      - run: make kubeconfig
      - run: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      - run: ./hack/test-smoke.sh
      - name: "Test data persistency after restarting the node"
        run: |
          make down
          make up
          sleep 30
          ./hack/test-smoke.sh
